package com.maria.sistemaincidencias;
// Generated 28-ene-2020 0:45:31 by Hibernate Tools 4.3.1



/**
 * AvisosId generated by hbm2java
 */
public class AvisosId  implements java.io.Serializable {


     private int codPersona;
     private int codEquipo;
     private String fechayhora;

    public AvisosId() {
    }

    public AvisosId(int codPersona, int codEquipo, String fechayhora) {
       this.codPersona = codPersona;
       this.codEquipo = codEquipo;
       this.fechayhora = fechayhora;
    }
   
    public int getCodPersona() {
        return this.codPersona;
    }
    
    public void setCodPersona(int codPersona) {
        this.codPersona = codPersona;
    }
    public int getCodEquipo() {
        return this.codEquipo;
    }
    
    public void setCodEquipo(int codEquipo) {
        this.codEquipo = codEquipo;
    }
    public String getFechayhora() {
        return this.fechayhora;
    }
    
    public void setFechayhora(String fechayhora) {
        this.fechayhora = fechayhora;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AvisosId) ) return false;
		 AvisosId castOther = ( AvisosId ) other; 
         
		 return (this.getCodPersona()==castOther.getCodPersona())
 && (this.getCodEquipo()==castOther.getCodEquipo())
 && ( (this.getFechayhora()==castOther.getFechayhora()) || ( this.getFechayhora()!=null && castOther.getFechayhora()!=null && this.getFechayhora().equals(castOther.getFechayhora()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodPersona();
         result = 37 * result + this.getCodEquipo();
         result = 37 * result + ( getFechayhora() == null ? 0 : this.getFechayhora().hashCode() );
         return result;
   }   


}


