package com.maria.harrypotterhibernate;
// Generated 27-ene-2020 16:20:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Casas generated by hbm2java
 */
public class Casas  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String animal;
     private String fantasma;
     private Set<Personajes> personajeses = new HashSet(0);
     
    public Casas() {
    }
	
    public Casas(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    
    public Casas(int id, String nombre, String animal, String fantasma) {
       this.id = id;
       this.nombre = nombre;
       this.animal = animal;
       this.fantasma = fantasma;
    }
    
    public Casas(int id, String nombre, String animal, String fantasma, Set personajeses) {
       this.id = id;
       this.nombre = nombre;
       this.animal = animal;
       this.fantasma = fantasma;
       this.personajeses = personajeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAnimal() {
        return this.animal;
    }
    
    public void setAnimal(String animal) {
        this.animal = animal;
    }
    public String getFantasma() {
        return this.fantasma;
    }
    
    public void setFantasma(String fantasma) {
        this.fantasma = fantasma;
    }
    public Set getPersonajeses() {
        return this.personajeses;
    }
    
    public void setPersonajeses(Set personajeses) {
        this.personajeses = personajeses;
    }
}


