package com.maria.harrypotterhibernate;
// Generated 27-ene-2020 16:20:30 by Hibernate Tools 4.3.1

/**
 * Mascotas generated by hbm2java
 */
public class Mascotas  implements java.io.Serializable {


     private int id;
     private Personajes personajes;
     private String nombre;

    public Mascotas() {
    }
	
    public Mascotas(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Mascotas(int id, Personajes personajes, String nombre) {
       this.id = id;
       this.personajes = personajes;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Personajes getPersonajes() {
        return this.personajes;
    }
    
    public void setPersonajes(Personajes personajes) {
        this.personajes = personajes;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}


